import type { GenerationResult, GeneratedFile } from './generator.js';

function pad(input: number): string {
    return String(input).padStart(2, '0');
}

export function makeTimestamp(date: Date): string {
    return `${date.getUTCFullYear()}${pad(date.getUTCMonth() + 1)}${pad(date.getUTCDate())}-${pad(date.getUTCHours())}${pad(date.getUTCMinutes())}${pad(date.getUTCSeconds())}`;
}

export function buildZipFileName(date: Date): string {
    return `backend-creator-${makeTimestamp(date)}.zip`;
}

export function buildMetadataFile(result: GenerationResult, date: Date): GeneratedFile {
    const warningLines = result.warnings.length > 0
        ? result.warnings.map((warning) => `- ${warning}`).join('\n')
        : '- None';
    const content = `# Generated by Backend Creator Playground

Generated at (UTC): ${date.toISOString()}
Models: ${result.modelCount}
Enums: ${result.enumCount}
Files: ${result.files.length}

## Warnings
${warningLines}

## Next Steps
1. pnpm install
2. cp .env.example .env
3. pnpm exec prisma migrate dev --name init
4. pnpm dev
`;
    return {
        path: 'GENERATED_BY_BACKEND_CREATOR.md',
        content,
    };
}
