import crypto from 'node:crypto';
import type { ParsedSchema, GeneratedFile, FieldDefinition } from '../../parser/types.js';
import { helpers } from '../template-engine.js';
import { resolveItemSelector, getExpressItemPath } from '../model-selector.js';

interface PostmanVariable {
    key: string;
    value: string;
    type?: string;
}

interface PostmanHeader {
    key: string;
    value: string;
}

interface PostmanUrl {
    raw: string;
    host: string[];
    path: string[];
    query?: Array<{ key: string; value: string; description?: string }>;
    variable?: Array<{ key: string; value: string; description?: string }>;
}

interface PostmanRequest {
    method: string;
    header: PostmanHeader[];
    url: PostmanUrl;
    body?: {
        mode: 'raw';
        raw: string;
        options: { raw: { language: 'json' } };
    };
}

interface PostmanItem {
    name: string;
    request: PostmanRequest;
}

interface PostmanFolder {
    name: string;
    item: PostmanItem[];
}

interface PostmanCollection {
    info: {
        name: string;
        _postman_id: string;
        schema: string;
        description: string;
    };
    variable: PostmanVariable[];
    item: PostmanFolder[];
}

/**
 * Generate a Postman Collection v2.1 JSON from the parsed schema.
 */
export function generateApiClientFiles(schema: ParsedSchema): GeneratedFile[] {
    const collection = buildCollection(schema);

    return [
        {
            path: 'postman-collection.json',
            content: JSON.stringify(collection, null, 2),
        },
    ];
}

function buildCollection(schema: ParsedSchema): PostmanCollection {
    const folders: PostmanFolder[] = [];

    // Auth endpoints (when @bcm.authModel is present)
    const authModel = schema.models.find(m => m.isAuthModel);
    if (authModel && authModel.identifierField && authModel.passwordField) {
        folders.push(buildAuthFolder(authModel.identifierField, authModel.passwordField));
    }

    // Per-model folders
    for (const model of schema.models) {
        folders.push(buildModelFolder(model, schema));
    }

    // Deterministic ID based on model names — avoids diff noise on regeneration
    const idSeed = schema.models.map(m => m.name).sort().join(',');
    const hash = crypto.createHash('sha256').update(idSeed).digest('hex');
    const postmanId = [
        hash.slice(0, 8), hash.slice(8, 12), hash.slice(12, 16), hash.slice(16, 20), hash.slice(20, 32),
    ].join('-');

    return {
        info: {
            name: 'Generated API',
            _postman_id: postmanId,
            schema: 'https://schema.getpostman.com/json/collection/v2.1.0/collection.json',
            description: 'REST API collection generated by Backend Creator (bcm)',
        },
        variable: [
            { key: 'baseUrl', value: 'http://localhost:3000', type: 'string' },
            { key: 'authToken', value: '', type: 'string' },
        ],
        item: folders,
    };
}

function buildAuthFolder(identifierField: string, passwordField: string): PostmanFolder {
    const items: PostmanItem[] = [
        {
            name: 'Login',
            request: {
                method: 'POST',
                header: [jsonHeader()],
                url: buildUrl('/api/v1/auth/login'),
                body: rawJsonBody({
                    [identifierField]: `example-${identifierField}`,
                    [passwordField]: 'password123',
                }),
            },
        },
        {
            name: 'Refresh Token',
            request: {
                method: 'POST',
                header: [jsonHeader()],
                url: buildUrl('/api/v1/auth/refresh'),
                body: rawJsonBody({ refreshToken: '00000000-0000-0000-0000-000000000000' }),
            },
        },
        {
            name: 'Logout',
            request: {
                method: 'POST',
                header: [jsonHeader()],
                url: buildUrl('/api/v1/auth/logout'),
                body: rawJsonBody({ refreshToken: '00000000-0000-0000-0000-000000000000' }),
            },
        },
    ];

    return { name: 'Auth', item: items };
}

function buildModelFolder(model: ParsedSchema['models'][number], schema: ParsedSchema): PostmanFolder {
    const modelCamel = helpers.toCamelCase(model.name);
    const modelPlural = helpers.pluralize(modelCamel);
    const basePath = `/api/v1/${modelPlural}`;
    const isProtected = model.directives.includes('protected') || model.directives.includes('auth');
    const itemSelector = resolveItemSelector(model);

    const items: PostmanItem[] = [];

    // List all
    items.push({
        name: `List all ${modelPlural}`,
        request: {
            method: 'GET',
            header: isProtected ? [authHeader()] : [],
            url: {
                ...buildUrl(basePath),
                query: [
                    { key: 'page', value: '1', description: 'Page number' },
                    { key: 'limit', value: '20', description: 'Items per page' },
                ],
            },
        },
    });

    // Create
    const createFields = getCreateFields(model);
    const sampleBody = buildSampleBody(createFields, schema);
    items.push({
        name: `Create ${modelCamel}`,
        request: {
            method: 'POST',
            header: [jsonHeader(), ...(isProtected ? [authHeader()] : [])],
            url: buildUrl(basePath),
            body: rawJsonBody(sampleBody),
        },
    });

    if (itemSelector) {
        const itemPath = `${basePath}${getExpressItemPath(itemSelector)}`;
        const pathVariables = itemSelector.fields.map(f => ({
            key: f,
            value: samplePathValue(model, f, schema),
            description: `${model.name} ${f}`,
        }));

        // Get by key
        items.push({
            name: `Get ${modelCamel} by key`,
            request: {
                method: 'GET',
                header: isProtected ? [authHeader()] : [],
                url: { ...buildUrl(itemPath), variable: pathVariables },
            },
        });

        // Update (PUT)
        items.push({
            name: `Update ${modelCamel}`,
            request: {
                method: 'PUT',
                header: [jsonHeader(), ...(isProtected ? [authHeader()] : [])],
                url: { ...buildUrl(itemPath), variable: pathVariables },
                body: rawJsonBody(sampleBody),
            },
        });

        // Partial update (PATCH)
        items.push({
            name: `Patch ${modelCamel}`,
            request: {
                method: 'PATCH',
                header: [jsonHeader(), ...(isProtected ? [authHeader()] : [])],
                url: { ...buildUrl(itemPath), variable: pathVariables },
                body: rawJsonBody(Object.fromEntries(Object.entries(sampleBody).slice(0, 1))),
            },
        });

        // Delete
        items.push({
            name: `Delete ${modelCamel}`,
            request: {
                method: 'DELETE',
                header: isProtected ? [authHeader()] : [],
                url: { ...buildUrl(itemPath), variable: pathVariables },
            },
        });
    }

    return { name: model.name, item: items };
}

function getCreateFields(model: ParsedSchema['models'][number]): FieldDefinition[] {
    return model.fields.filter(
        (f) =>
            !f.isRelation &&
            !f.isId &&
            !f.directives.includes('hidden') &&
            !f.directives.includes('readonly') &&
            (!f.isServerDefault || f.directives.includes('writeOnly'))
    );
}

function buildSampleBody(fields: FieldDefinition[], schema: ParsedSchema): Record<string, unknown> {
    const body: Record<string, unknown> = {};
    for (const field of fields) {
        body[field.name] = sampleValue(field, schema);
    }
    return body;
}

function sampleValue(field: FieldDefinition, schema: ParsedSchema): unknown {
    if (field.isEnum) {
        const enumDef = schema.enums.find(e => e.name === field.type);
        if (enumDef && enumDef.values.length > 0) return enumDef.values[0];
        return 'VALUE';
    }

    switch (field.type) {
        case 'String': return `example-${field.name}`;
        case 'Int': return 1;
        case 'Float':
        case 'Decimal': return 1.5;
        case 'Boolean': return true;
        case 'DateTime': return '2024-01-01T00:00:00.000Z';
        case 'BigInt': return 1;
        case 'Json': return {};
        default: return `example-${field.name}`;
    }
}

function samplePathValue(model: ParsedSchema['models'][number], fieldName: string, schema: ParsedSchema): string {
    const field = model.fields.find(f => f.name === fieldName);
    if (!field) return 'example-id';

    if (field.isEnum) {
        const enumDef = schema.enums.find(e => e.name === field.type);
        if (enumDef && enumDef.values.length > 0) return enumDef.values[0];
    }

    switch (field.type) {
        case 'Int':
        case 'BigInt': return '1';
        case 'String': return 'example-id';
        default: return 'example-id';
    }
}

function buildUrl(path: string): PostmanUrl {
    // Convert Express-style :param to Postman-style :param (they're the same)
    const segments = path.split('/').filter(Boolean);
    return {
        raw: `{{baseUrl}}${path}`,
        host: ['{{baseUrl}}'],
        path: segments,
    };
}

function jsonHeader(): PostmanHeader {
    return { key: 'Content-Type', value: 'application/json' };
}

function authHeader(): PostmanHeader {
    return { key: 'Authorization', value: 'Bearer {{authToken}}' };
}

function rawJsonBody(data: Record<string, unknown>) {
    return {
        mode: 'raw' as const,
        raw: JSON.stringify(data, null, 2),
        options: { raw: { language: 'json' as const } },
    };
}
